
/* 
    ? lecture 66 : Construct Tree from Inorder and Preorder
    ? link : https://www.geeksforgeeks.org/problems/construct-tree-1/1

    Given two arrays representing the inorder and preorder traversals of a binary tree, construct the tree and return the root node of the constructed tree.
    
    Note: The output is written in postorder traversal.
    
    Examples:
    
    Input: inorder[] = [1, 6, 8, 7], preorder[] = [1, 6, 7, 8]
    Output: [8, 7, 6, 1]
    Explanation: The tree will look like
           1 
              \  
                6
                   \
                     7
                  /
               8
    Input: inorder[] = [3, 1, 4, 0, 5, 2], preorder[] = [0, 1, 3, 4, 2, 5]
    Output: [3, 4, 1, 5, 2, 0]
    Explanation: The tree will look like
           0
        /     \
       1       2
     /   \    /
    3    4   5
    Input: inorder[] = [2, 5, 4, 1, 3], preorder[] = [1, 4, 5, 2, 3]
    Output: [2, 5, 4, 3, 1]
    Explanation: The tree will look like
            1
         /     \
        4       3
       /
      5
     /
    2

*/

#include<iostream>
using namespace std;

class  {
    public:

};

int main() {


 return 0;
}